version: "3.3"

services:
  eatjs-v2.1:
    container_name: eatjs-v2.1
    build: ./server/
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "1337:1337"
    restart: always
    logging:
      options:
        max-size: "200k"
        max-file: "10"