module.exports = self => {
    self.express = require('express')
    self.body_parser = require('body-parser')
    self.cors = require('cors')
    self.morgan = require('morgan')
    self.async = require('async')
    self._ = require('lodash')
    self.colors = require('colors')
    self.path = require('path')
    self.mongoose = require('mongoose')
    self.web_socket = require('ws')
    self.request = require('request')
    self.fs = require('fs')
    self.path = require('path')
    self.redis = require('redis')
    self.uuid = require('uuid')
    self.jwt = require('jsonwebtoken')
    self.jwt_decode = require('jwt-decode')
}